name: CI/CD Pipeline

on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

jobs:
  #   lint:
  #     name: Lint Code
  #     runs-on: ubuntu-latest
  #     steps:
  #       - name: Checkout code
  #         uses: actions/checkout@v3

  #       # Cache node_modules
  #       - name: Set up Node.js
  #         uses: actions/setup-node@v3
  #         with:
  #           node-version: "20" # Use the appropriate node version
  #           cache: "npm"

  #       - name: Install dependencies
  #         run: npm ci

  #       - name: Run Lint
  #         run: npm run lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Cache node_modules
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm test -- --ci --coverage

  build:
    name: Build the application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Cache node_modules
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./build

  deploy:
    name: Deploy to Netlify
    runs-on: ubuntu-latest
    needs: build # Ensure this runs after the build job completes
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      # - name: Install dependencies
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: "20"
      #     cache: "npm"

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      # - name: Install dependencies
      #   run: npm ci
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: ./build
      # - name: Build Project
      #   run: npm run build

      - name: Deploy to Netlify
        run: netlify deploy --prod --dir=build --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} --site=${{ secrets.NETLIFY_SITE_ID }}
